const routes = {
  projects: "Projects",
  projectsMain: "ProjectsMain",
  projectFilter: "ProjectFilter",
  projectDropdown: "ProjectDropdown",
  need: "Need",
  needs: "Needs",
  interestedNeeds: "interestedNeeds",
  needDetail: "NeedDetails",
  allocation: "Allocation",
  allocations: "Allocations",
  allocationInfo: "AllocationInfo",
  allocationStateOptions: "AllocationStateOptions",
  notification: "Notifications",
  more: "more",
  filter: "filter",
  needsFilter: "needsfilter",
  createNeed: "createNeed",
  app: "app",
  onBoarding: "Onboarding",
  login: "login",
  signup: "signup",
  retrievePassword: "retrievePassword",
  verification: "verification",
  checkEmail: "checkEmail",
  changePassword: "changePassword",
  manageAccount: "manageAccount",
  passwordReset: "passwordReset",
  about: "about",
  termsAndConditions: "termsAndConditions",
  aboutTracka: "aboutTracka",
  logout: "logout",
  intialSetup: "setup",
  projectDetails: "projectDetails",
  reportProject: "reportProject",
  settings: "Settings",
  moresettings: "MoreSettings",
  preference: "Preference",
  support: "support",
  interestedProject: "interestedProject",
  moresupport: "MoreSupport",
  feedback: "feedback"
};

export default routes;
