export const USER_KEY = "user_key";
export const FACEBOOK_APP_ID = "655829575764897";
export const SETUP_KEY = "SETUP_KEY";

export const GET_PROJECTS_KEY = "GET_PROJECTS";

export const GET_MINISTRIES_KEY = "GET_MINISTRIES";

export const GET_NEW_PROJECTS_KEY = "GET_NEW_PROJECTS";
export const GET_NEW_PROJECT_KEY = "GET_NEW_PROJECT";



export const GET_PROJECTS_BY_ID_KEY = "GET_PROJECTS_BY_ID";


export const GET_PROJECTS_NOTIFICATION_KEY = "GET_PROJECTS_NOTIFICATION_KEY";

export const GET_SUBSCRIBE_KEY = "GET_SUBSCRIBE_KEY"

export const GET_SUBSCRIBE_FETCH_KEY = "GET_SUBSCRIBE_FETCH_KEY"


export const GET_REPORTED_KEY = "GET_REPORTED_KEY"

export const NOTIFICATION_KEY = "GET_NOTIFICATION_KEY"

export const NOTIFICATION_LIST_KEY = "GET_NOTIFICATION_LIST_KEY"

export const NATIVE_PUSH_TOKEN = 2476
export const NATIVE_PUSH_TOKEN_LONG = "VH2qcQVX7fvRzbG2bysb63"

export const PUSHER_TOKEN = "1d4eb20c505b49e623d0"