export const projects = [
  {
    id: 1,
    name: "Field Overlay",
    description: "Constrution of ICT knowledge center and funishing",
    status: "in_progress",
    category: "Education",
    lga: "Minna",
    state: "Niger",
    budget: 10000000000,
    reporters: 22,
    imageUrl: "",
  },
  {
    id: 2,
    name: "",
    description: "Constrution of 3rd Mainland Bridge",
    status: "completed",
    category: "Construction",
    lga: "Surulere",
    state: "Lagos",
    budget: 3000000000,
    reporters: 29,
    imageUrl: "",
  },
  {
    id: 3,
    name: "",
    description: "Constrution of Orphanage",
    status: "awarded",
    category: "Agriculture",
    lga: "Kabul",
    state: "Abuja",
    budget: 100000000,
    reporters: 105,
    imageUrl: "",
  },
];
